# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:37
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, verbose_name='bank account number')),
                ('is_supervisor', models.BooleanField(verbose_name='supervisor')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='cargo.Dock')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
