# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_fire', models.BooleanField(verbose_name='fire hazard')),
                ('has_chemical', models.BooleanField(verbose_name='chemical hazard')),
            ],
        ),
        migrations.CreateModel(
            name='Dock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dock_number', models.CharField(max_length=15, unique=True, verbose_name='dock number')),
            ],
        ),
        migrations.CreateModel(
            name='DockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=5)),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='cargo.Dock')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_number', models.CharField(max_length=15, unique=True, verbose_name='ship number')),
            ],
        ),
        migrations.AddField(
            model_name='docklog',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargo.Ship'),
        ),
        migrations.AddField(
            model_name='dock',
            name='ship_in',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dock', to='cargo.Ship'),
        ),
        migrations.AddField(
            model_name='container',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='cargo.Ship'),
        ),
    ]
